runtime: nodejs16
env: standard
instance_class: F1
env_variables:
  MONGODB_URI: "mongodb+srv://sahilkhadtare:sahil@cluster0.dijdfcd.mongodb.net/?retryWrites=true&w=majority"
  NODE_ENV: production
  SECRET: "NextJs"
